[ticket/10710] Fixed pre-commit hook whitespace stuff.
Not functional, no idea why.

PHPBB3-10710

diff --git a/git-tools/hooks/pre-commit b/git-tools/hooks/pre-commit
--- a/git-tools/hooks/pre-commit
+++ b/git-tools/hooks/pre-commit
@@ -84,28 +84,24 @@ fi
 
 # Compile a list of changed files
 FILES=`git diff --name-only HEAD^`
+ERRORS=''
 
-# Attempt to fix whitespace issues
-for FILE in `egrep -l '(\s$| {1,3}\t)' $FILES`
+for FILE in `egrep -l '(\s$|^ {1,3}\t)' $FILES`
 do
-	# Remove trailing whitespace
-	(sed -i 's/[ 	]*$//' $FILE > /dev/null 2>&1 || sed -i '' -E 's/[ 	]*$//' $FILE)
-
-	# Remove spaces before tabs
-	(sed -i 's/ {1,3}	/	/' $FILE > /dev/null 2>&1 || sed -i '' -E 's/ {1,3}	/	/' $FILE)
-
-	# Add to git
-	git add $FILE
-	echo "Automatically fixed whitespace in $FILE"
+	ERRORS="$ERRORS\nWhitespace issue detected in $FILE"
 done
 
-# Check for new lines at end of file, add if it is not there
 for FILE in $FILES
 do
 	if ! tail -c1 $FILE | read _
-	then    
-		echo > $FILE
-		git add $FILE
-		echo "Added new line to end of $FILE"
+	then
+		ERRORS="$ERRORS\nNo newline at end of $FILE"
 	fi
 done
+
+# Abort commit if any errors
+if [ "$ERRORS" != '' ]
+then
+	echo -e "Commit has been aborted:$ERRORS"
+	exit 1
+fi
