[ticket/10724] Adding the check for trailling spaces in lines
This adds the check for trailling whitespace characters in lines.
It checks for all the lines that contain, at least, one whitespace character
and then it prints them. While pritting them, it shows the same information as
the php lint. The filename and the line where the finding occured. Additionally,
because grep was used, it shows the text of the line where the situation
happened

PHPBB3-10724

diff --git a/git-tools/hooks/pre-commit b/git-tools/hooks/pre-commit
--- a/git-tools/hooks/pre-commit
+++ b/git-tools/hooks/pre-commit
@@ -26,6 +26,8 @@ fi
 
 syntaxerror=0
 syntaxerrors=""
+spaceserror=0
+spaceserrors=""
 
 if ! which $PHP_BIN >/dev/null 2>&1
 then
@@ -76,6 +78,16 @@ do
 		syntaxerrors=$(echo "$syntaxerrors"; echo "$result" |sed -e "s@in - on@in $filename on@g")
 	fi
 
+	# check content for wrong trailling whitespace characters
+	result=$(git cat-file -p $sha | grep -E --line-number --regexp="[[:space:]]$")
+
+	if [ $? -eq 0 ]
+	then
+		spaceserror=2
+		# Swap back in correct filenames
+		spaceserrors=$(echo "$spaceserrors"; echo "->$filename:"; echo "$result")
+	fi
+
 done
 unset IFS
 
@@ -83,5 +95,15 @@ if [ $syntaxerror -eq 1 ]
 then
 	echo -e "PHP Syntax check failed:";
 	echo -e "$syntaxerrors" | grep "^Parse error:"
-	exit 1
+fi
+
+if [ $spaceserror -eq 1 ]
+then
+	echo -e -n "\nWrong line trailling characters:";
+	echo -e "$spaceserrors"
+fi
+
+if [ $syntaxerror -eq 1 -o $spaceserror -eq 2 ]
+then
+	exit $(($syntaxerror + $spaceserror))
 fi
